### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by mbikovitsky** [Hurtak/hello#22]
It would be really nice to have this extension on Firefox. I did some testing and it appears that the current version will work without any code modifications. The only thing to do is package the extension and [publish](https://extensionworkshop.com/documentation/publish/signing-and-distribution-overview/) it to the add-on repository.

**Comment by Hurtak** [comment]
Good idea, I submitted it to the Firefox store, it might take a few weeks to get reviewed. I will keep you updated.

**Comment by Hurtak** [comment]
Ok it seems to be approved and live on the store https://addons.mozilla.org/en-US/firefox/addon/hello-new-tab/
It works on my PC but let me know if there are any issues
